#!/usr/bin/env bash
set -Eeuo pipefail

script_path=$(readlink -f -- "${BASH_SOURCE[0]}")
repo_dir=$(cd -- "$(dirname -- "$script_path")/.." && pwd)
if [[ -f "$repo_dir/.env" ]]; then source "$repo_dir/.env"; fi

: "${FOREMAN_TASK:?Foreman did not provide FOREMAN_TASK}"
: "${FOREMAN_REMOVE_WORKTREE:?Foreman did not provide FOREMAN_REMOVE_WORKTREE}"
[[ "$FOREMAN_TASK" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || {
    echo "invalid task slug: $FOREMAN_TASK" >&2
    exit 1
}

round_dir="$repo_dir/rounds/$FOREMAN_TASK"
[[ -d "$round_dir" ]] || {
    echo "round directory is missing: $round_dir" >&2
    exit 1
}

cache_root=${TILEOPS_CACHE_ROOT:-${XDG_CACHE_HOME:-$HOME/.cache}/tileops-runner}
worker_env="$round_dir/.worker-env"
if [[ -f "$worker_env" ]]; then
    # Generated by setup-worktree.sh with shell-escaped values.
    # shellcheck disable=SC1090
    source "$worker_env"
fi

if [[ -n ${TILEOPS_DOCKER_BOOTSTRAP:-} ]]; then "$TILEOPS_DOCKER_BOOTSTRAP" >&2; fi
if [[ -n ${TILEOPS_DOCKER_HOST:-} ]]; then export DOCKER_HOST=$TILEOPS_DOCKER_HOST; fi

# The agent ran inside the round container, so its transcripts are in there too.
if [[ -n ${TILEOPS_WORKER_CONTAINER:-} ]] && \
    docker container inspect "$TILEOPS_WORKER_CONTAINER" >/dev/null 2>&1; then
    mkdir -p "$round_dir/session"
    if docker exec "$TILEOPS_WORKER_CONTAINER" \
        test -d /root/.claude/projects/-workspace-round; then
        docker exec "$TILEOPS_WORKER_CONTAINER" \
            tar -C /root/.claude/projects/-workspace-round -cf - . \
            | tar -C "$round_dir/session" -xf -
        python3 - "$round_dir/session" "$FOREMAN_TASK" <<'PY'
import datetime
import hashlib
import json
import sys
from pathlib import Path

destination = Path(sys.argv[1])
records = []
for path in sorted(destination.rglob("*.jsonl")):
    data = path.read_bytes()
    records.append(
        {
            "file": str(path.relative_to(destination)),
            "bytes": len(data),
            "lines": data.count(b"\n"),
            "sha256": hashlib.sha256(data).hexdigest(),
        }
    )
manifest = {
    "task": sys.argv[2],
    "collected": datetime.datetime.now(datetime.timezone.utc).astimezone().isoformat(),
    "transcripts": records,
}
(destination / "MANIFEST.json").write_text(
    json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
)
print(f"archived {len(records)} agent transcript(s) in {destination}")
PY
    else
        echo "warning: the round container holds no agent transcript" >&2
    fi
fi

# What the round changed in TileFoundry leaves as one patch against the base it
# started from. The source tree itself is scratch; the patch is the artifact that
# becomes an upstream issue and pull request.
foundry_patch="$round_dir/foundry.patch"
if [[ -n ${TILEOPS_FOUNDRY_SOURCE:-} && -n ${TILEOPS_FOUNDRY_BASE:-} \
    && -e "$TILEOPS_FOUNDRY_SOURCE/.git" ]]; then
    git -C "$TILEOPS_FOUNDRY_SOURCE" add --all
    git -C "$TILEOPS_FOUNDRY_SOURCE" diff --binary --cached "$TILEOPS_FOUNDRY_BASE" \
        >"$foundry_patch"
    if [[ -s "$foundry_patch" ]]; then
        printf 'wrote TileFoundry patch against %s: %s\n' \
            "${TILEOPS_FOUNDRY_BASE:0:12}" "$foundry_patch"
    else
        rm -f -- "$foundry_patch"
    fi
fi

if [[ "$FOREMAN_REMOVE_WORKTREE" == 1 ]]; then
    declare -a containers=()
    if [[ -n ${TILEOPS_WORKER_CONTAINER:-} ]] && \
        docker container inspect "$TILEOPS_WORKER_CONTAINER" >/dev/null 2>&1; then
        containers+=("$(docker container inspect --format '{{.Id}}' \
            "$TILEOPS_WORKER_CONTAINER")")
    fi
    while IFS= read -r container; do
        [[ -n "$container" ]] && containers+=("$container")
    done < <(docker ps -aq --filter "label=tileops.task=$FOREMAN_TASK")
    if (( ${#containers[@]} )); then
        remove_container() {
            local container=$1
            local deadline=$((SECONDS + 60))
            local output
            while docker container inspect "$container" >/dev/null 2>&1; do
                if output=$(docker rm -f "$container" 2>&1); then
                    return 0
                fi
                if grep -qiE 'already in progress|no such container' <<<"$output"; then
                    (( SECONDS < deadline )) || {
                        echo "timed out waiting for container removal: $container" >&2
                        return 1
                    }
                    sleep 0.5
                    continue
                fi
                printf '%s\n' "$output" >&2
                return 1
            done
        }

        while IFS= read -r container; do
            [[ -n "$container" ]] && remove_container "$container"
        done < <(printf '%s\n' "${containers[@]}" | sort -u)
        printf 'removed round container(s) for %s\n' "$FOREMAN_TASK"
    fi

    ssh_config_dir="$cache_root/ssh-config"
    if [[ -d "$ssh_config_dir" ]]; then
        find "$ssh_config_dir" -maxdepth 1 -type f \
            -name "tileops-$FOREMAN_TASK-*" -delete
    fi
    if [[ -n ${TILEOPS_FOUNDRY_SOURCE:-} && -e "$TILEOPS_FOUNDRY_SOURCE/.git" ]]; then
        tilefoundry_repo=${TILEFOUNDRY_REPO:-}
        if [[ -n "$tilefoundry_repo" ]]; then
            git -C "$tilefoundry_repo" worktree remove --force \
                "$TILEOPS_FOUNDRY_SOURCE" || rm -rf -- "$TILEOPS_FOUNDRY_SOURCE"
            git -C "$tilefoundry_repo" worktree prune
        else
            rm -rf -- "$TILEOPS_FOUNDRY_SOURCE"
        fi
        printf 'removed round TileFoundry source for %s\n' "$FOREMAN_TASK"
    fi

    ssh_key_dir="$cache_root/round-ssh/$FOREMAN_TASK"
    if [[ -d "$ssh_key_dir" ]]; then
        rm -f -- "$ssh_key_dir/id_ed25519" "$ssh_key_dir/id_ed25519.pub"
        rmdir -- "$ssh_key_dir"
    fi
    printf 'removed round SSH state for %s\n' "$FOREMAN_TASK"
fi
