#!/usr/bin/env bash
set -Eeuo pipefail

script_path=$(readlink -f -- "${BASH_SOURCE[0]}")
repo_dir=$(cd -- "$(dirname -- "$script_path")/.." && pwd)
if [[ -f "$repo_dir/.env" ]]; then source "$repo_dir/.env"; fi

: "${FOREMAN_TASK:?Foreman did not provide FOREMAN_TASK}"
: "${FOREMAN_REMOVE_WORKTREE:?Foreman did not provide FOREMAN_REMOVE_WORKTREE}"
[[ "$FOREMAN_TASK" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || {
    echo "invalid task slug: $FOREMAN_TASK" >&2
    exit 1
}

round_dir="$repo_dir/rounds/$FOREMAN_TASK"
[[ -d "$round_dir" ]] || {
    echo "round directory is missing: $round_dir" >&2
    exit 1
}

python3 - "${PI_SESSIONS_DIR:-$HOME/.pi/agent/sessions}" \
    "$round_dir" "$FOREMAN_TASK" <<'PY'
from __future__ import annotations

import datetime
import hashlib
import json
import shutil
import sys
from pathlib import Path


session_root = Path(sys.argv[1]).expanduser()
round_dir = Path(sys.argv[2]).resolve()
task = sys.argv[3]
sources: list[tuple[Path, dict]] = []

for source in sorted(session_root.glob("*/*.jsonl")):
    try:
        with source.open(encoding="utf-8") as stream:
            header = json.loads(stream.readline())
    except (OSError, json.JSONDecodeError):
        continue
    cwd = header.get("cwd")
    if isinstance(cwd, str) and Path(cwd).name == task:
        sources.append((source, header))

if not sources:
    print(f"warning: no Pi transcript found for task {task} under {session_root}", file=sys.stderr)

destination = round_dir / "session"
destination.mkdir(parents=True, exist_ok=True)
records = []
for source, header in sources:
    data = source.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    target = destination / source.name
    if target.exists() and hashlib.sha256(target.read_bytes()).hexdigest() != digest:
        target = destination / f"{header.get('id', source.parent.name)}-{source.name}"
    shutil.copy2(source, target)
    records.append(
        {
            "file": target.name,
            "source": str(source),
            "session_id": header.get("id"),
            "cwd": header.get("cwd"),
            "bytes": len(data),
            "lines": data.count(b"\n"),
            "sha256": digest,
        }
    )

manifest = {
    "task": task,
    "collected": datetime.datetime.now(datetime.timezone.utc).astimezone().isoformat(),
    "transcripts": records,
}
temporary = destination / ".MANIFEST.json.tmp"
temporary.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
temporary.replace(destination / "MANIFEST.json")
print(f"archived {len(records)} Pi transcript(s) in {destination}")
PY

if [[ "$FOREMAN_REMOVE_WORKTREE" == 1 ]]; then
    cache_root=${TILEOPS_CACHE_ROOT:-${XDG_CACHE_HOME:-$HOME/.cache}/tileops-runner}
    worker_env="$round_dir/.worker-env"
    if [[ -f "$worker_env" ]]; then
        # Generated by setup-worktree.sh with shell-escaped values.
        # shellcheck disable=SC1090
        source "$worker_env"
    fi

    if [[ -n ${TILEOPS_DOCKER_BOOTSTRAP:-} ]]; then "$TILEOPS_DOCKER_BOOTSTRAP"; fi
    if [[ -n ${TILEOPS_DOCKER_HOST:-} ]]; then export DOCKER_HOST=$TILEOPS_DOCKER_HOST; fi

    declare -a containers=()
    if [[ -n ${TILEOPS_WORKER_CONTAINER:-} ]] && \
        docker container inspect "$TILEOPS_WORKER_CONTAINER" >/dev/null 2>&1; then
        containers+=("$(docker container inspect --format '{{.Id}}' \
            "$TILEOPS_WORKER_CONTAINER")")
    fi
    while IFS= read -r container; do
        [[ -n "$container" ]] && containers+=("$container")
    done < <(docker ps -aq --filter "label=tileops.task=$FOREMAN_TASK")
    if (( ${#containers[@]} )); then
        remove_container() {
            local container=$1
            local deadline=$((SECONDS + 60))
            local output
            while docker container inspect "$container" >/dev/null 2>&1; do
                if output=$(docker rm -f "$container" 2>&1); then
                    return 0
                fi
                if grep -qiE 'already in progress|no such container' <<<"$output"; then
                    (( SECONDS < deadline )) || {
                        echo "timed out waiting for container removal: $container" >&2
                        return 1
                    }
                    sleep 0.5
                    continue
                fi
                printf '%s\n' "$output" >&2
                return 1
            done
        }

        while IFS= read -r container; do
            [[ -n "$container" ]] && remove_container "$container"
        done < <(printf '%s\n' "${containers[@]}" | sort -u)
        printf 'removed round container(s) for %s\n' "$FOREMAN_TASK"
    fi

    ssh_config_dir="$cache_root/ssh-config"
    if [[ -d "$ssh_config_dir" ]]; then
        find "$ssh_config_dir" -maxdepth 1 -type f \
            -name "tileops-$FOREMAN_TASK-*" -delete
    fi
    ssh_key_dir="$cache_root/round-ssh/$FOREMAN_TASK"
    if [[ -d "$ssh_key_dir" ]]; then
        rm -f -- "$ssh_key_dir/id_ed25519" "$ssh_key_dir/id_ed25519.pub"
        rmdir -- "$ssh_key_dir"
    fi
    printf 'removed round SSH state for %s\n' "$FOREMAN_TASK"
fi
